name: Webpage Monitor

on:
  schedule:
    # 10分に1回実行する設定
    - cron: '*/10 * * * *'
  workflow_dispatch: # 手動実行用

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: レポジトリをチェックアウト
      uses: actions/checkout@v4

    - name: Pythonのセットアップ
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: ライブラリのインストール
      run: |
        python -m pip install --upgrade pip
        pip install --default-timeout=100 requests beautifulsoup4

    - name: 監視スクリプトを実行
      env:
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
      run: |
        python monitor_komiharu.py
        python monitor_hiccorohee.py
        python monitor_ticketdive.py

    - name: 状態(last_hash.txt)の変化を保存してGitHubにコミット
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add last_hash_komiharu.txt last_hash_hiccorohee.txt last_hash_ticketdive.txt
        # 変更がある場合のみコミットしてプッシュする
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update hashes" && git push)